version: "3.9"
services:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  db:
    image: mysql
    restart: always
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-secret}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_DATABASE: '${DB_DATABASE}'
